Repository openshift/dynamic-plugin-sdk, pull requests merged in 2023-10, with the labels that each got.

#237 Publish lib-utils 4.0.0 (PF5 support)
  packages/lib-utils/package.json
Labels: approved, lgtm

#234 RHCLOUD-28058: successful call to k8sDeleteResource results in error
  packages/lib-utils/src/types/k8s.ts
  packages/lib-utils/src/utils/common-fetch.ts
  reports/lib-utils.api.md
Labels: approved, lgtm, jira/valid-reference

#239 Validate dependency values in DynamicRemotePlugin
  packages/lib-core/src/runtime/PluginLoader.ts
  packages/lib-webpack/package.json
  packages/lib-webpack/src/webpack/DynamicRemotePlugin.ts
  yarn.lock
Labels: approved, lgtm

#240 Disallow empty string dependency values in DynamicRemotePlugin
  packages/lib-webpack/src/webpack/DynamicRemotePlugin.ts
Labels: approved, lgtm

#227 Generate plugin manifest after asset hashing phase.
  packages/lib-webpack/src/webpack/GenerateManifestPlugin.ts
  packages/lib-webpack/src/webpack/PatchEntryCallbackPlugin.ts
  packages/sample-plugin/webpack.config.ts
Labels: lifecycle/stale, ok-to-test, approved, lgtm

#241 Improve core logic and useResolvedExtensions hook
  packages/common/src/errors/ErrorWithCause.ts
  packages/lib-core/src/index.ts
  packages/lib-core/src/runtime/PluginLoader.ts
  packages/lib-core/src/runtime/PluginStore.ts
  packages/lib-core/src/runtime/coderefs.ts
  packages/lib-core/src/runtime/useResolvedExtensions.ts
  packages/lib-webpack/src/webpack/DynamicRemotePlugin.ts
  packages/lib-webpack/src/webpack/GenerateManifestPlugin.ts
  reports/lib-core.api.md
Labels: approved, lgtm

#243 Add python to installed system packages in CI buildroot image
  docker/Dockerfile.ci-operator-buildroot
Labels: approved, lgtm

#244 Fix Prow CI issues due to recent base image changes
  docker/Dockerfile.ci-operator-buildroot
Labels: approved, lgtm

#242 Update lib-utils version post npm publish
  packages/lib-utils/package.json
Labels: approved, lgtm
